[package]
name = "iowatch"
version = "0.2.0"
authors = ["Mauri de Souza Meneguzzo <mauri870@gmail.com>"]
edition = "2018"

[dependencies]
notify = "4.0.0"
thiserror = "1.0.23"
anyhow = "1.0"
structopt = "0.2.14"
